# Configuration for probot-stale - https://github.com/probot/stale
daysUntilStale: 21
daysUntilClose: 7
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
